services:
  database:
    image: postgres:latest
    container_name: vote-broadcast-server-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  