@host = localhost:8080
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNSIsInVzZXJuYW1lIjoidXNlciIsImV4cCI6MTc0MzUxMjgzOCwiaWF0IjoxNzQzNTExMDM4fQ.mvUH2aJ-CdMl3NMkeImUJhssQvNdGOns28dVwHTqdD4

// HTTP Tests
### Register User
POST {{host}}/api/register
Content-Type: application/json
Accept: application/json

{
  "username": "user1234123",
  "password": "pass1234"
}

### Login User
POST {{host}}/api/login
Content-Type: application/json
Accept: application/json

{
  "username": "user",
  "password": "pass"
}

### Get Polls
GET {{host}}/api/polls
Accept: application/json

### Get Poll
GET {{host}}/api/polls/13
Accept: application/json

### Create Poll
POST {{host}}/api/polls
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "title": "Poll Title",
  "options": [
    {
      "id": 0,
      "text": "Option 1"
    },
    {
      "id": 0,
      "text": "Option 2"
    }
  ],
  "type": 1
}

### GetVotes
GET {{host}}/api/votes/13

### Create Vote
POST {{host}}/api/vote
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "poll_id": 13,
  "options_id": [
    10, 11, 12
  ]
}