port: 8080

services:
  auth:
    url: "auth-service:5001"
    routes:
      - path: /api/register
        method: POST
      - path: /api/login
        method: POST

  poll:
    url: "poll-service:5002"
    routes:
      - path: /api/polls
        method: GET
      - path: /api/polls
        method: POST
      - path: /api/polls/:id
        method: GET

  vote:
    url: "vote-service:5003"
    routes:
      - path: /api/votes
        method: POST
      - path: /api/votes/:id
        method: GET

  websocket:
    url: "websocket-service:5004"
    routes:
      - path: /ws
        method: GET
