port: 8080

services:
  auth:
    url: "http://localhost:5001"
    routes:
      - path: /api/register
        method: POST
      - path: /api/login
        method: POST

  poll:
    url: "http://localhost:5002"
    routes:
      - path: /api/polls
        method: GET
      - path: /api/polls
        method: POST
      - path: /api/polls/{id}
        method: GET

  vote:
    url: "http://localhost:5003"
    routes:
      - path: /api/vote
        method: POST
      - path: /api/vote/{poll_id}
        method: GET

  websocket:
    url: "http://localhost:5004"
    routes:
      - path: /ws
        method: GET
