@host=localhost:5004
@url=grpc://{{host}}/websocket.WebSocketService

### Send Polls
GRPC {{url}}/GetPolls

{
  "polls": [
    {
      "id": 1,
      "title": "govno"
    },
    {
      "id": 2,
      "title": "sdgf"
    }
  ]
}

### Send Votes
GRPC {{url}}/GetVotes

{
  "poll_id": 1,
  "options": [
    {
      "id": 1,
      "count_votes": 2,
      "users": [
        {
          "id": 1,
          "name": "ivan"
        },
        {
          "id": 2,
          "name": "petya"
        }
      ]
    },
    {
      "id": 2,
      "count_votes": 3,
      "users": [
        {
          "id": 3,
          "name": "kolya"
        }
      ]
    }
  ]
}